@echo off
REM ****************************************************************************
REM Vivado (TM) v2025.1 (64-bit)
REM
REM Filename    : elaborate.bat
REM Simulator   : AMD Vivado Simulator
REM Description : Script for elaborating the compiled design
REM
REM Generated by Vivado on Sat Aug 29 11:52:03 +0800 2026
REM SW Build 6140274 on Thu May 22 00:12:29 MDT 2025
REM
REM Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
REM Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
REM
REM usage: elaborate.bat
REM
REM ****************************************************************************

set xv_cxl_lib_path="C:/Xilinx/2025.1/Vivado/data/xsim"
set xv_cpt_lib_path=""
set xv_ext_lib_path=""
set xv_boost_lib_path="C:/Xilinx/2025.1/Vivado/tps/boost_1_72_0"

set xv_cxl_win_path=C:/Xilinx/2025.1/Vivado/data/xsim
set PATH=;%PATH%

REM link design libraries
echo "xsc --shared_systemc -lib xil_defaultlib -o libdpi.dll"
call xsc  --shared_systemc -lib xil_defaultlib -o libdpi.dll 2> xsc_err.log
set exit_code=%errorlevel%
call type xsc.log >> elaborate_xsc.log
call type xsc_err.log >> elaborate_xsc.log
call type xsc_err.log
if "%exit_code%"=="1" goto END
REM elaborate design
echo "xelab --incr --debug typical --relax --mt 2 --include "%xv_boost_lib_path%" -L xil_defaultlib -L blk_mem_gen_v8_4_11 -L axis_infrastructure_v1_1_1 -L axis_data_fifo_v2_0_17 -L uvm -L unisims_ver -L unimacro_ver -L secureip -L xpm -sv_root "." -sc_lib libdpi.dll --snapshot train_behav xil_defaultlib.train xil_defaultlib.glbl -log elaborate.log"
call xelab  --incr --debug typical --relax --mt 2 --include "%xv_boost_lib_path%" -L xil_defaultlib -L blk_mem_gen_v8_4_11 -L axis_infrastructure_v1_1_1 -L axis_data_fifo_v2_0_17 -L uvm -L unisims_ver -L unimacro_ver -L secureip -L xpm -sv_root "." -sc_lib libdpi.dll --snapshot train_behav xil_defaultlib.train xil_defaultlib.glbl -log elaborate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
