create_clock -name clk1 -period 16.000 -waveform {0 8}  [get_ports clk1]
create_clock -name clk2 -period 24.000 -waveform {0 12} [get_ports clk2]
set_clock_groups -asynchronous -group [get_clocks clk1] -group [get_clocks clk2]

set_false_path -from [get_clocks clk1] -to [get_clocks clk2]
set_false_path -from [get_clocks clk2] -to [get_clocks clk1]

set_property ASYNC_REG TRUE [get_cells {aer_rx_inst/cdc_sync_inst/gen_cdc_sync.sync_chain_reg[0][0]}]
set_property ASYNC_REG TRUE [get_cells {aer_tx_inst/cdc_sync_inst/gen_cdc_sync.sync_chain_reg[0][0]}]
set_property ASYNC_REG TRUE [get_cells {aer_tx_inst/m_axis_tdata[0]}]
set_property ASYNC_REG TRUE [get_cells {aer_tx_inst/m_axis_tdata[1]}]
set_property ASYNC_REG TRUE [get_cells {aer_tx_inst/m_axis_tdata[2]}]
set_property ASYNC_REG TRUE [get_cells {aer_tx_inst/m_axis_tdata[3]}]
set_property ASYNC_REG TRUE [get_cells {aer_tx_inst/m_axis_tdata[4]}]
set_property ASYNC_REG TRUE [get_cells {aer_tx_inst/m_axis_tdata[5]}]
set_property ASYNC_REG TRUE [get_cells {aer_tx_inst/m_axis_tdata[6]}]
set_property ASYNC_REG TRUE [get_cells {aer_tx_inst/m_axis_tdata[7]}]