@echo off
REM ****************************************************************************
REM Vivado (TM) v2025.1 (64-bit)
REM
REM Filename    : compile.bat
REM Simulator   : AMD Vivado Simulator
REM Description : Script for compiling the simulation design source files
REM
REM Generated by Vivado on Wed Aug 26 14:32:51 +0800 2026
REM SW Build 6140274 on Thu May 22 00:12:29 MDT 2025
REM
REM Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
REM Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
REM
REM usage: compile.bat
REM
REM ****************************************************************************

set xv_cxl_lib_path="C:/Xilinx/2025.1/Vivado/data/xsim"
set xv_cpt_lib_path=""
set xv_ext_lib_path=""
set xv_boost_lib_path="C:/Xilinx/2025.1/Vivado/tps/boost_1_72_0"

REM compile CPP design sources
echo "xsc -c --gcc_compile_options "-I%xv_boost_lib_path%" -work xil_defaultlib -f Neuron_Update_I_tb_cpp.prj"
call xsc  -c --gcc_compile_options "-I%xv_boost_lib_path%" -work xil_defaultlib -f Neuron_Update_I_tb_cpp.prj 2> xsc_err.log
call type xsc.log >> compile.log
call type xsc_err.log >> compile.log
call type xsc_err.log
REM compile Verilog/System Verilog design sources
echo "xvlog --incr --relax -L uvm -prj Neuron_Update_I_tb_vlog.prj"
call xvlog  --incr --relax -L uvm -prj Neuron_Update_I_tb_vlog.prj -log xvlog.log
call type xvlog.log > compile.log
if "%errorlevel%"=="1" goto END
if "%errorlevel%"=="0" goto SUCCESS
:END
exit 1
:SUCCESS
exit 0
