@echo off
REM ****************************************************************************
REM Vivado (TM) v2025.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : AMD Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Wed Aug 26 14:33:03 +0800 2026
REM SW Build 6140274 on Thu May 22 00:12:29 MDT 2025
REM
REM Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
REM Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************

set xv_cxl_lib_path="C:/Xilinx/2025.1/Vivado/data/xsim"
set xv_cpt_lib_path=""
set xv_ext_lib_path=""

set xv_cxl_win_path=C:/Xilinx/2025.1/Vivado/data/xsim
set PATH=;%PATH%

REM simulate design
echo "xsim Neuron_Update_I_tb_behav -key {Behavioral:train:Functional:Neuron_Update_I_tb} -tclbatch Neuron_Update_I_tb.tcl -view C:/MARTIN/verilog/Xilinx/projects_vivado/SNN_accelerator/SNN_accelerator.srcs/train/imports/train/train_behav.wcfg -log simulate.log"
call xsim  Neuron_Update_I_tb_behav -key {Behavioral:train:Functional:Neuron_Update_I_tb} -tclbatch Neuron_Update_I_tb.tcl -view C:/MARTIN/verilog/Xilinx/projects_vivado/SNN_accelerator/SNN_accelerator.srcs/train/imports/train/train_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
